import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import Provider from "@/providers/Provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
            <div className="min-h-screen bg-white text-black dark:bg-[#0f172a] dark:text-[#ddd] transition-colors duration-300 ">
              <div className="mx-auto px-10 md:px-20 lg:px-40 max-w-[475px] sm:max-w-[640px] md:max-w-[768px] lg:max-w-[1024px] xl:max-w-[1366px] 2xl:max-w-[1536px]">
                <Navbar/>
                  {children}
                <Footer/>
              </div>
            </div>
        </Provider>
          
        
      </body>
    </html>
  );
}
